#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$BACKEND_DIR/.." && pwd)"

COMPOSE_FILE="${COMPOSE_FILE:-$ROOT_DIR/docker-compose.yml}"
DB_USER="${DB_USER:-game}"
DB_NAME="${DB_NAME:-game}"
DATABASE_URL="${DATABASE_URL:-postgres://game:game@localhost:5432/game?sslmode=disable}"
MIGRATIONS_DIR="${MIGRATIONS_DIR:-$BACKEND_DIR/db/migrations}"
GOOSE_VERSION="v3.26.0"

if [[ ! -d "$MIGRATIONS_DIR" ]]; then
  echo "migration directory does not exist: $MIGRATIONS_DIR" >&2
  exit 1
fi

query_database() {
  local query="$1"
  if command -v psql >/dev/null 2>&1; then
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atqc "$query"
    return
  fi
  docker compose -f "$COMPOSE_FILE" exec -T postgres \
    psql -v ON_ERROR_STOP=1 -U "$DB_USER" -d "$DB_NAME" -Atqc "$query"
}

run_database_sql() {
  if command -v psql >/dev/null 2>&1; then
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1
    return
  fi
  docker compose -f "$COMPOSE_FILE" exec -T postgres \
    psql -v ON_ERROR_STOP=1 -U "$DB_USER" -d "$DB_NAME"
}

latest_migration_version() {
  local migration filename version_text version latest=0
  for migration in "$MIGRATIONS_DIR"/*.sql; do
    [[ -f "$migration" ]] || continue
    filename="${migration##*/}"
    version_text="${filename%%_*}"
    [[ "$version_text" =~ ^[0-9]+$ ]] || continue
    version=$((10#$version_text))
    if (( version > latest )); then
      latest=$version
    fi
  done
  (( latest > 0 )) || {
    echo "no numbered SQL migrations found in $MIGRATIONS_DIR" >&2
    return 1
  }
  echo "$latest"
}

adopt_legacy_schema_if_needed() {
  local version_table_exists worlds_table_exists latest legacy_version=13
  version_table_exists="$(query_database "SELECT to_regclass('public.goose_db_version') IS NOT NULL;")"
  [[ "$version_table_exists" == "t" ]] && return 0

  worlds_table_exists="$(query_database "SELECT to_regclass('public.worlds') IS NOT NULL;")"
  [[ "$worlds_table_exists" == "t" ]] || return 0

  if [[ "$MIGRATIONS_DIR" != "$BACKEND_DIR/db/migrations" ]]; then
    echo "legacy schema has no Goose ledger; use the repository migration directory or reset the database" >&2
    exit 1
  fi

  # Older disposable databases were created by the raw bootstrap loop and
  # have no Goose ledger. Only adopt one when the final landed schema marker is
  # present; an incomplete schema must be reset rather than silently marked
  # current.
  if [[ "$(query_database "SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='chronicle_entries'
        AND column_name='related_obligation_id'
    ) AND to_regclass('public.chronicle_obligation_outcome_unique') IS NOT NULL;")" != "t" ]]; then
    echo "existing schema has no Goose ledger and cannot be safely adopted; reset the database" >&2
    exit 1
  fi

  latest="$(latest_migration_version)"
  if (( latest < legacy_version )); then
    echo "repository migrations do not contain the legacy bootstrap version $legacy_version" >&2
    exit 1
  fi

  # The original development bootstrap applied migrations 1 through 13 without
  # a ledger. Baseline that known schema version, rather than the repository's
  # current latest version, so migrations added after the old bootstrap still
  # run against preserved local databases.
  echo "Adopting the existing fully bootstrapped schema at Goose version $legacy_version"
  run_database_sql <<SQL
CREATE TABLE IF NOT EXISTS goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);
INSERT INTO goose_db_version (version_id, is_applied)
SELECT version_id, false FROM (VALUES (0::bigint)) AS baseline(version_id)
UNION ALL
SELECT generate_series(1, $legacy_version), true;
SQL
}

adopt_legacy_schema_if_needed

cd "$BACKEND_DIR"
exec go run "github.com/pressly/goose/v3/cmd/goose@$GOOSE_VERSION" \
  -dir "$MIGRATIONS_DIR" postgres "$DATABASE_URL" up
