package application

import (
	"context"
	"fmt"
	"sort"
	"time"

	"game/backend/internal/balance"
	"game/backend/internal/calendar"
	chronicle_domain "game/backend/internal/domain/chronicle"
	reportdomain "game/backend/internal/domain/report"
	"game/backend/internal/port"
	"game/backend/internal/simulation"
)

type Alert struct {
	Level   string `json:"level"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

type FarmReport struct {
	HouseholdID   string        `json:"household_id"`
	HouseholdName string        `json:"household_name"`
	WorldID       string        `json:"world_id"`
	Tick          int64         `json:"tick"`
	GameDay       int64         `json:"game_day"`
	Calendar      calendar.Date `json:"calendar"`
	// HistoricalDate is retained for legacy Go fixtures only; it is not part of
	// the player-facing report contract.
	HistoricalDate string                      `json:"-"`
	Season         simulation.Season           `json:"season"`
	SupplyDays     float64                     `json:"supply_days"`
	Resources      map[string]float64          `json:"resources"`
	Characters     []port.CharacterRecord      `json:"characters"`
	Assignments    []port.AssignmentRecord     `json:"assignments"`
	Alerts         []Alert                     `json:"alerts"`
	ChangeWindow   ChangeWindow                `json:"change_window"`
	RecentChanges  []port.ChronicleEntryRecord `json:"recent_changes"`
	Attention      []reportdomain.Item         `json:"attention"`
	Decisions      []reportdomain.Item         `json:"decisions"`
}

type ChangeWindow struct {
	FromTick int64 `json:"from_tick"`
	ToTick   int64 `json:"to_tick"`
}

type ReportService struct {
	Store   port.ReportReader
	Balance simulation.BalanceConfig
}

const (
	recentChangeWindowSeconds  = int64(24 * time.Hour / time.Second)
	maxRecentChangeWindowTicks = int64(12)
)

func recentChangeWindowTicks(tickDurationSeconds int32) int64 {
	if tickDurationSeconds <= 0 {
		return 1
	}

	seconds := int64(tickDurationSeconds)
	ticks := (recentChangeWindowSeconds + seconds - 1) / seconds
	if ticks < 1 {
		return 1
	}
	if ticks > maxRecentChangeWindowTicks {
		return maxRecentChangeWindowTicks
	}
	return ticks
}

func NewReportService(store port.ReportReader) *ReportService {
	return &ReportService{Store: store, Balance: balance.V03()}
}

func (s *ReportService) FarmReport(ctx context.Context, householdID string) (FarmReport, error) {
	snap, err := s.Store.GetHouseholdReport(ctx, householdID)
	if err != nil {
		return FarmReport{}, err
	}
	supply := snap.State.SupplyDays(s.Balance)
	// Alerts is retained as a compatibility field for older clients. New
	// clients consume structured Attention items below; no localized prose is
	// generated by the backend.
	alerts := make([]Alert, 0)
	gameDay := calendar.GameDay(snap.CurrentGameDay)
	var historical time.Time
	if snap.GameDaysPerTickNum > 0 && snap.GameDaysPerTickDen > 0 {
		breakdown := calendar.BreakdownOf(gameDay)
		_ = breakdown
	} else {
		var err error
		historical, err = (calendar.Clock{
			StartDate:   snap.HistoricalStart,
			DaysPerTick: calendar.Rational{Numerator: int64(snap.HistoricalDaysPerTickNum), Denominator: int64(snap.HistoricalDaysPerTickDen)},
		}).DateAtTick(snap.CurrentTick)
		if err != nil {
			return FarmReport{}, err
		}
	}
	for i := range snap.Characters {
		var err error
		if snap.GameDaysPerTickNum > 0 && snap.GameDaysPerTickDen > 0 {
			snap.Characters[i].Age, err = calendar.Age(calendar.GameDay(snap.Characters[i].BirthGameDay), gameDay)
		} else {
			birthDate, parseErr := time.Parse(time.DateOnly, snap.Characters[i].BirthDate)
			if parseErr != nil {
				return FarmReport{}, fmt.Errorf("character %s birth date: %w", snap.Characters[i].ID, parseErr)
			}
			snap.Characters[i].Age, err = calendar.AgeOn(birthDate, historical)
		}
		if err != nil {
			return FarmReport{}, fmt.Errorf("character %s age: %w", snap.Characters[i].ID, err)
		}
	}
	assignments := snap.Assignments
	if assignments == nil {
		assignments = make([]port.AssignmentRecord, 0)
	}
	characters := snap.Characters
	if characters == nil {
		characters = make([]port.CharacterRecord, 0)
	}
	attentionInput := reportdomain.Input{CurrentTick: snap.CurrentTick, CurrentGameDay: snap.CurrentGameDay, SupplyDays: supply}
	for _, c := range characters {
		attentionInput.Characters = append(attentionInput.Characters, reportdomain.Character{ID: c.ID, Name: c.Name, Fatigue: c.Fatigue})
	}
	var recent []port.ChronicleEntryRecord
	var political []port.PoliticalReportDemand
	var obligations []port.ContractReportObligation
	if reader, ok := s.Store.(port.FarmReportReader); ok {
		windowTicks := recentChangeWindowTicks(snap.TickDurationSeconds)
		from := snap.CurrentTick - windowTicks + 1
		if from < 0 {
			from = 0
		}
		recent, err = reader.ListRecentChronicleForReport(ctx, householdID, from, 50)
		if err != nil {
			return FarmReport{}, err
		}
		recent = selectSignificantChanges(recent)
		political, err = reader.ListPendingPoliticalDemandsForReport(ctx, householdID)
		if err != nil {
			return FarmReport{}, err
		}
		obligations, err = reader.ListContractObligationsForReport(ctx, householdID)
		if err != nil {
			return FarmReport{}, err
		}
	}
	for _, d := range political {
		expiresGameDay := d.ExpiresGameDay
		if expiresGameDay == 0 {
			expiresGameDay = tickGameDay(snap, d.ExpiresTick)
		}
		attentionInput.PoliticalDemands = append(attentionInput.PoliticalDemands, reportdomain.PoliticalDemand{ID: d.ID, ActorName: d.ActorName, ExpiresTick: d.ExpiresTick, ExpiresGameDay: expiresGameDay})
	}
	for _, o := range obligations {
		attentionInput.ContractObligations = append(attentionInput.ContractObligations, reportdomain.ContractObligation{ID: o.ID, ResourceType: o.ResourceType, QuantityMilli: o.QuantityMilli, DueArrivalTick: o.DueArrivalTick, ExpectedArrivalTick: o.ExpectedArrivalTick, DueGameDay: o.DueGameDay, ExpectedArrivalGameDay: o.ExpectedArrivalGameDay})
	}
	attention := reportdomain.BuildAttention(attentionInput)
	decisions := reportdomain.BuildDecisions(attentionInput)
	if recent == nil {
		recent = make([]port.ChronicleEntryRecord, 0)
	}
	if attention == nil {
		attention = make([]reportdomain.Item, 0)
	}
	if decisions == nil {
		decisions = make([]reportdomain.Item, 0)
	}
	windowTicks := recentChangeWindowTicks(snap.TickDurationSeconds)
	fromTick := snap.CurrentTick - windowTicks + 1
	if fromTick < 0 {
		fromTick = 0
	}
	breakdown := calendar.BreakdownOf(gameDay)
	season := simulation.Season(breakdown.ProductionSeason)
	if snap.GameDaysPerTickNum == 0 || snap.GameDaysPerTickDen == 0 {
		season = simulation.SeasonForDate(historical)
	}
	return FarmReport{
		HouseholdID: snap.HouseholdID, HouseholdName: snap.HouseholdName, WorldID: snap.WorldID,
		Tick: snap.CurrentTick, GameDay: int64(gameDay), Calendar: breakdown,
		HistoricalDate: func() string {
			if historical.IsZero() {
				return ""
			}
			return historical.Format(time.DateOnly)
		}(), Season: season,
		SupplyDays: supply,
		Resources:  map[string]float64{"provisions": float64(snap.State.ProvisionsMilli) / 1000, "wood": float64(snap.State.WoodMilli) / 1000, "trade_goods": float64(snap.State.TradeGoodsMilli) / 1000, "silver": float64(snap.State.SilverMilli) / 1000},
		Characters: characters, Assignments: assignments, Alerts: alerts,
		ChangeWindow: ChangeWindow{FromTick: fromTick, ToTick: snap.CurrentTick}, RecentChanges: recent,
		Attention: attention, Decisions: decisions,
	}, nil
}

func selectSignificantChanges(entries []port.ChronicleEntryRecord) []port.ChronicleEntryRecord {
	importance := map[string]int{
		chronicle_domain.ShipmentArrived: 3, chronicle_domain.ContractObligationBroken: 3, chronicle_domain.ContractObligationLate: 3,
		chronicle_domain.PoliticalDemandAutoResolved: 3, chronicle_domain.EmergencyFoodWorkScheduled: 3,
		chronicle_domain.ContractObligationFulfilled: 2, chronicle_domain.PoliticalDemandReceived: 2, chronicle_domain.PoliticalDemandResolved: 2,
		chronicle_domain.MarketPurchase: 2, chronicle_domain.MarketSale: 2, chronicle_domain.ContractAccepted: 2, chronicle_domain.ContractRejected: 2,
		chronicle_domain.AssignmentScheduled: 1, chronicle_domain.AssignmentCompleted: 1, chronicle_domain.ContractShipmentDispatched: 1,
	}
	sort.SliceStable(entries, func(i, j int) bool {
		pi, pj := importance[entries[i].EntryType], importance[entries[j].EntryType]
		if pi != pj {
			return pi > pj
		}
		if entries[i].OccurredTick != entries[j].OccurredTick {
			return entries[i].OccurredTick > entries[j].OccurredTick
		}
		if entries[i].EntryType != entries[j].EntryType {
			return entries[i].EntryType < entries[j].EntryType
		}
		return entries[i].ID < entries[j].ID
	})
	if len(entries) > 3 {
		entries = entries[:3]
	}
	return entries
}
