// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMarketRouteDistance = `-- name: GetMarketRouteDistance :one
SELECT distance_class
FROM location_routes
WHERE world_id = $1::uuid
  AND origin_location_id = $2::uuid
  AND destination_location_id = $3::uuid
`

type GetMarketRouteDistanceParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
	Column3 pgtype.UUID
}

func (q *Queries) GetMarketRouteDistance(ctx context.Context, arg GetMarketRouteDistanceParams) (string, error) {
	row := q.db.QueryRow(ctx, getMarketRouteDistance, arg.Column1, arg.Column2, arg.Column3)
	var distance_class string
	err := row.Scan(&distance_class)
	return distance_class, err
}

const listActiveMarketOffers = `-- name: ListActiveMarketOffers :many
SELECT o.id::text AS id, o.world_id::text AS world_id,
       o.seller_household_id::text AS seller_household_id,
       o.origin_location_id::text AS origin_location_id, o.resource_code,
       o.quantity_remaining_milli, o.price_per_unit_milli, o.created_tick,
       o.expires_tick, o.status
FROM market_offers o
JOIN worlds w ON w.id = o.world_id
WHERE o.world_id = $1::uuid
  AND o.status = 'active'
  AND (o.expires_tick IS NULL OR o.expires_tick >= w.current_tick)
ORDER BY o.created_tick, o.id
`

type ListActiveMarketOffersRow struct {
	ID                     string
	WorldID                string
	SellerHouseholdID      string
	OriginLocationID       string
	ResourceCode           string
	QuantityRemainingMilli int64
	PricePerUnitMilli      int64
	CreatedTick            int64
	ExpiresTick            pgtype.Int8
	Status                 string
}

func (q *Queries) ListActiveMarketOffers(ctx context.Context, dollar_1 pgtype.UUID) ([]ListActiveMarketOffersRow, error) {
	rows, err := q.db.Query(ctx, listActiveMarketOffers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMarketOffersRow{}
	for rows.Next() {
		var i ListActiveMarketOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.SellerHouseholdID,
			&i.OriginLocationID,
			&i.ResourceCode,
			&i.QuantityRemainingMilli,
			&i.PricePerUnitMilli,
			&i.CreatedTick,
			&i.ExpiresTick,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMarketOffer = `-- name: LockMarketOffer :one
SELECT id::text AS id, world_id::text AS world_id,
       seller_household_id::text AS seller_household_id,
       origin_location_id::text AS origin_location_id, resource_code,
       quantity_remaining_milli, price_per_unit_milli, created_tick,
       expires_tick, status
FROM market_offers
WHERE id = $1::uuid
FOR UPDATE
`

type LockMarketOfferRow struct {
	ID                     string
	WorldID                string
	SellerHouseholdID      string
	OriginLocationID       string
	ResourceCode           string
	QuantityRemainingMilli int64
	PricePerUnitMilli      int64
	CreatedTick            int64
	ExpiresTick            pgtype.Int8
	Status                 string
}

func (q *Queries) LockMarketOffer(ctx context.Context, dollar_1 pgtype.UUID) (LockMarketOfferRow, error) {
	row := q.db.QueryRow(ctx, lockMarketOffer, dollar_1)
	var i LockMarketOfferRow
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.SellerHouseholdID,
		&i.OriginLocationID,
		&i.ResourceCode,
		&i.QuantityRemainingMilli,
		&i.PricePerUnitMilli,
		&i.CreatedTick,
		&i.ExpiresTick,
		&i.Status,
	)
	return i, err
}

const updateMarketOfferAfterPurchase = `-- name: UpdateMarketOfferAfterPurchase :one
UPDATE market_offers
SET quantity_remaining_milli = $2, status = $3, updated_at = now()
WHERE id = $1::uuid AND status = 'active' AND quantity_remaining_milli = $4
RETURNING id::text AS id, world_id::text AS world_id,
          seller_household_id::text AS seller_household_id,
          origin_location_id::text AS origin_location_id, resource_code,
          quantity_remaining_milli, price_per_unit_milli, created_tick,
          expires_tick, status
`

type UpdateMarketOfferAfterPurchaseParams struct {
	Column1                  pgtype.UUID
	QuantityRemainingMilli   int64
	Status                   string
	QuantityRemainingMilli_2 int64
}

type UpdateMarketOfferAfterPurchaseRow struct {
	ID                     string
	WorldID                string
	SellerHouseholdID      string
	OriginLocationID       string
	ResourceCode           string
	QuantityRemainingMilli int64
	PricePerUnitMilli      int64
	CreatedTick            int64
	ExpiresTick            pgtype.Int8
	Status                 string
}

func (q *Queries) UpdateMarketOfferAfterPurchase(ctx context.Context, arg UpdateMarketOfferAfterPurchaseParams) (UpdateMarketOfferAfterPurchaseRow, error) {
	row := q.db.QueryRow(ctx, updateMarketOfferAfterPurchase,
		arg.Column1,
		arg.QuantityRemainingMilli,
		arg.Status,
		arg.QuantityRemainingMilli_2,
	)
	var i UpdateMarketOfferAfterPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.SellerHouseholdID,
		&i.OriginLocationID,
		&i.ResourceCode,
		&i.QuantityRemainingMilli,
		&i.PricePerUnitMilli,
		&i.CreatedTick,
		&i.ExpiresTick,
		&i.Status,
	)
	return i, err
}
