// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	CharacterID  pgtype.UUID
	ActivityType string
	Intensity    string
	StartsTick   int64
	EndsTick     int64
	Status       string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Character struct {
	ID                 pgtype.UUID
	HouseholdID        pgtype.UUID
	Name               string
	LaborCapacityMilli int32
	Health             int32
	Fatigue            int32
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	BirthDate          pgtype.Date
}

type CharacterSkill struct {
	CharacterID      pgtype.UUID
	SkillCode        string
	Level            int32
	TrainingProgress int32
}

type ChronicleEntry struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	OccurredTick        int64
	EntryType           string
	SubjectCharacterID  pgtype.UUID
	RelatedHouseholdID  pgtype.UUID
	RelatedContractID   pgtype.UUID
	Data                []byte
	CreatedAt           pgtype.Timestamptz
	RelatedShipmentID   pgtype.UUID
	RelatedAssignmentID pgtype.UUID
}

type Contract struct {
	ID                pgtype.UUID
	WorldID           pgtype.UUID
	PartyAHouseholdID pgtype.UUID
	PartyBHouseholdID pgtype.UUID
	StartsTick        int64
	EndsTick          int64
	IntervalTicks     int32
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ContractObligation struct {
	ID                  pgtype.UUID
	ContractID          pgtype.UUID
	DebtorHouseholdID   pgtype.UUID
	CreditorHouseholdID pgtype.UUID
	ResourceCode        string
	QuantityMilli       int64
	DueArrivalTick      int64
	ShipmentID          pgtype.UUID
	Status              string
	FulfilledTick       pgtype.Int8
	UpdatedAt           pgtype.Timestamptz
}

type ContractTerm struct {
	ContractID          pgtype.UUID
	DebtorHouseholdID   pgtype.UUID
	CreditorHouseholdID pgtype.UUID
	ResourceCode        string
	QuantityMilli       int64
}

type Household struct {
	ID             pgtype.UUID
	WorldID        pgtype.UUID
	OwnerPlayerID  pgtype.UUID
	LocationID     pgtype.UUID
	Name           string
	Specialization pgtype.Text
	CreatedTick    int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type HouseholdBuilding struct {
	ID            pgtype.UUID
	HouseholdID   pgtype.UUID
	BuildingType  string
	Level         int32
	CompletedTick int64
}

type HouseholdDecision struct {
	ID                pgtype.UUID
	HouseholdID       pgtype.UUID
	WorldEventID      pgtype.UUID
	DecisionType      string
	AvailableFromTick int64
	ExpiresTick       int64
	Status            string
	SelectedOption    pgtype.Text
	DefaultOption     string
	Parameters        []byte
	ResolvedTick      pgtype.Int8
	CreatedAt         pgtype.Timestamptz
}

type Location struct {
	ID               pgtype.UUID
	WorldID          pgtype.UUID
	ParentLocationID pgtype.UUID
	Name             string
	LocationType     string
	CreatedAt        pgtype.Timestamptz
}

type LocationRoute struct {
	WorldID               pgtype.UUID
	OriginLocationID      pgtype.UUID
	DestinationLocationID pgtype.UUID
	DistanceClass         string
	CreatedAt             pgtype.Timestamptz
}

type MarketOffer struct {
	ID                     pgtype.UUID
	WorldID                pgtype.UUID
	SellerHouseholdID      pgtype.UUID
	OriginLocationID       pgtype.UUID
	ResourceCode           string
	QuantityRemainingMilli int64
	PricePerUnitMilli      int64
	CreatedTick            int64
	ExpiresTick            pgtype.Int8
	Status                 string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type OutboxEvent struct {
	ID          pgtype.UUID
	WorldID     pgtype.UUID
	EventType   string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Attempts    int32
}

type Player struct {
	ID                  pgtype.UUID
	ExternalAuthSubject string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type PoliticalActor struct {
	ID         pgtype.UUID
	WorldID    pgtype.UUID
	LocationID pgtype.UUID
	Name       string
	ActorType  string
}

type PoliticalRelationship struct {
	HouseholdID      pgtype.UUID
	PoliticalActorID pgtype.UUID
	Standing         int32
}

type ProcessedWorldTick struct {
	WorldID     pgtype.UUID
	Tick        int64
	ProcessedAt pgtype.Timestamptz
}

type Relationship struct {
	WorldID              pgtype.UUID
	SourceHouseholdID    pgtype.UUID
	TargetHouseholdID    pgtype.UUID
	Trust                int32
	FirstInteractionTick pgtype.Int8
	UpdatedAt            pgtype.Timestamptz
}

type RelationshipEvent struct {
	ID                pgtype.UUID
	WorldID           pgtype.UUID
	SourceHouseholdID pgtype.UUID
	TargetHouseholdID pgtype.UUID
	EventType         string
	TrustDelta        int32
	OccurredTick      int64
	RelatedContractID pgtype.UUID
	RelatedShipmentID pgtype.UUID
	Data              []byte
}

type ResourceStock struct {
	HouseholdID   pgtype.UUID
	ResourceCode  string
	QuantityMilli int64
	UpdatedAt     pgtype.Timestamptz
}

type ResourceType struct {
	Code     string
	Category string
	Tradable bool
}

type Shipment struct {
	ID                    pgtype.UUID
	WorldID               pgtype.UUID
	SenderHouseholdID     pgtype.UUID
	ReceiverHouseholdID   pgtype.UUID
	OriginLocationID      pgtype.UUID
	DestinationLocationID pgtype.UUID
	ResourceCode          string
	QuantityMilli         int64
	DepartureTick         int64
	ExpectedArrivalTick   int64
	ActualArrivalTick     pgtype.Int8
	TransportCostMilli    int64
	Status                string
	Metadata              []byte
	CreatedAt             pgtype.Timestamptz
}

type World struct {
	ID                       pgtype.UUID
	Name                     string
	HistoricalStartDate      pgtype.Date
	CurrentTick              int64
	TickDurationSeconds      int32
	NextTickAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	HistoricalDaysPerTickNum int32
	HistoricalDaysPerTickDen int32
}

type WorldEvent struct {
	ID         pgtype.UUID
	WorldID    pgtype.UUID
	LocationID pgtype.UUID
	EventType  string
	StartsTick int64
	EndsTick   pgtype.Int8
	Parameters []byte
	CreatedAt  pgtype.Timestamptz
}
