// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: politics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyPoliticalScoreDelta = `-- name: ApplyPoliticalScoreDelta :exec
INSERT INTO political_relationships(world_id, household_id, political_actor_id, standing, updated_at)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        GREATEST(-100, LEAST(100, $4)), now())
ON CONFLICT (household_id, political_actor_id)
DO UPDATE SET standing = GREATEST(-100, LEAST(100, political_relationships.standing + EXCLUDED.standing)), updated_at = now()
`

type ApplyPoliticalScoreDeltaParams struct {
	WorldID          pgtype.UUID
	HouseholdID      pgtype.UUID
	PoliticalActorID pgtype.UUID
	ScoreDelta       interface{}
}

func (q *Queries) ApplyPoliticalScoreDelta(ctx context.Context, arg ApplyPoliticalScoreDeltaParams) error {
	_, err := q.db.Exec(ctx, applyPoliticalScoreDelta,
		arg.WorldID,
		arg.HouseholdID,
		arg.PoliticalActorID,
		arg.ScoreDelta,
	)
	return err
}

const assignmentOverlaps = `-- name: AssignmentOverlaps :one
SELECT EXISTS(SELECT 1 FROM assignments
 WHERE character_id = $1::uuid
   AND status IN ('planned','active')
   AND starts_tick <= $2 AND ends_tick >= $3) AS overlaps
`

type AssignmentOverlapsParams struct {
	CharacterID pgtype.UUID
	EndsTick    int64
	StartsTick  int64
}

func (q *Queries) AssignmentOverlaps(ctx context.Context, arg AssignmentOverlapsParams) (bool, error) {
	row := q.db.QueryRow(ctx, assignmentOverlaps, arg.CharacterID, arg.EndsTick, arg.StartsTick)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const autoResolvePoliticalDecision = `-- name: AutoResolvePoliticalDecision :execrows
UPDATE household_decisions
SET status = 'auto_resolved', selected_option = $1, resolved_tick = $2,
    standing_delta = $3, updated_at = now()
WHERE id = $4::uuid AND status = 'pending'
`

type AutoResolvePoliticalDecisionParams struct {
	SelectedOption pgtype.Text
	ResolvedTick   pgtype.Int8
	StandingDelta  pgtype.Int4
	DecisionID     pgtype.UUID
}

func (q *Queries) AutoResolvePoliticalDecision(ctx context.Context, arg AutoResolvePoliticalDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, autoResolvePoliticalDecision,
		arg.SelectedOption,
		arg.ResolvedTick,
		arg.StandingDelta,
		arg.DecisionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRulerServiceAssignment = `-- name: CreateRulerServiceAssignment :one
INSERT INTO assignments(household_id, character_id, activity_type, intensity, starts_tick, ends_tick, status, metadata)
VALUES ($1::uuid, $2::uuid, 'ruler_service', 'normal',
        $3, $4, 'planned', $5::jsonb)
RETURNING id::text AS id
`

type CreateRulerServiceAssignmentParams struct {
	HouseholdID pgtype.UUID
	CharacterID pgtype.UUID
	StartsTick  int64
	EndsTick    int64
	Metadata    []byte
}

func (q *Queries) CreateRulerServiceAssignment(ctx context.Context, arg CreateRulerServiceAssignmentParams) (string, error) {
	row := q.db.QueryRow(ctx, createRulerServiceAssignment,
		arg.HouseholdID,
		arg.CharacterID,
		arg.StartsTick,
		arg.EndsTick,
		arg.Metadata,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deductResourceStock = `-- name: DeductResourceStock :exec
UPDATE resource_stocks SET quantity_milli = quantity_milli - $1, updated_at = now()
WHERE household_id = $2::uuid AND resource_code = $3
  AND quantity_milli >= $1
`

type DeductResourceStockParams struct {
	Amount       int64
	HouseholdID  pgtype.UUID
	ResourceCode string
}

func (q *Queries) DeductResourceStock(ctx context.Context, arg DeductResourceStockParams) error {
	_, err := q.db.Exec(ctx, deductResourceStock, arg.Amount, arg.HouseholdID, arg.ResourceCode)
	return err
}

const householdExists = `-- name: HouseholdExists :one
SELECT EXISTS(SELECT 1 FROM households WHERE id = $1::uuid) AS exists
`

func (q *Queries) HouseholdExists(ctx context.Context, householdID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, householdExists, householdID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHouseholdDecision = `-- name: InsertHouseholdDecision :execrows
INSERT INTO household_decisions(
  household_id, world_id, world_event_id, decision_type,
  available_from_tick, expires_tick, available_from_game_day, expires_game_day,
  status, default_option, parameters
) VALUES (
  $1::uuid, $2::uuid, $3::uuid,
  $4, $5, $6,
  $7, $8,
  'pending', 'refuse', $9::jsonb
)
ON CONFLICT (household_id, world_event_id) WHERE world_event_id IS NOT NULL DO NOTHING
`

type InsertHouseholdDecisionParams struct {
	HouseholdID          pgtype.UUID
	WorldID              pgtype.UUID
	WorldEventID         pgtype.UUID
	DecisionType         string
	AvailableFromTick    int64
	ExpiresTick          int64
	AvailableFromGameDay int64
	ExpiresGameDay       int64
	Parameters           []byte
}

func (q *Queries) InsertHouseholdDecision(ctx context.Context, arg InsertHouseholdDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertHouseholdDecision,
		arg.HouseholdID,
		arg.WorldID,
		arg.WorldEventID,
		arg.DecisionType,
		arg.AvailableFromTick,
		arg.ExpiresTick,
		arg.AvailableFromGameDay,
		arg.ExpiresGameDay,
		arg.Parameters,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPoliticalChronicle = `-- name: InsertPoliticalChronicle :execrows
INSERT INTO chronicle_entries(
 household_id, occurred_tick, occurred_game_day, entry_type, related_household_decision_id,
 related_political_actor_id, related_assignment_id, data
) VALUES ($1::uuid, $2, $3, $4,
          $5::uuid, $6::uuid,
          NULLIF($7::text, '')::uuid, $8::jsonb)
ON CONFLICT (household_id, related_household_decision_id, entry_type)
WHERE related_household_decision_id IS NOT NULL DO NOTHING
`

type InsertPoliticalChronicleParams struct {
	HouseholdID     pgtype.UUID
	OccurredTick    int64
	OccurredGameDay int64
	EntryType       string
	DecisionID      pgtype.UUID
	ActorID         pgtype.UUID
	AssignmentID    string
	Data            []byte
}

func (q *Queries) InsertPoliticalChronicle(ctx context.Context, arg InsertPoliticalChronicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPoliticalChronicle,
		arg.HouseholdID,
		arg.OccurredTick,
		arg.OccurredGameDay,
		arg.EntryType,
		arg.DecisionID,
		arg.ActorID,
		arg.AssignmentID,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPoliticalReceivedChronicle = `-- name: InsertPoliticalReceivedChronicle :exec
INSERT INTO chronicle_entries(household_id, occurred_tick, occurred_game_day, entry_type,
  related_household_decision_id, related_political_actor_id, data)
SELECT d.household_id, $1, $2, 'political_demand_received', d.id,
       $3::uuid, $4::jsonb
FROM household_decisions d
WHERE d.household_id = $5::uuid
  AND d.world_event_id = $6::uuid
ON CONFLICT (household_id, related_household_decision_id, entry_type)
WHERE related_household_decision_id IS NOT NULL DO NOTHING
`

type InsertPoliticalReceivedChronicleParams struct {
	OccurredTick    int64
	OccurredGameDay int64
	ActorID         pgtype.UUID
	Data            []byte
	HouseholdID     pgtype.UUID
	WorldEventID    pgtype.UUID
}

func (q *Queries) InsertPoliticalReceivedChronicle(ctx context.Context, arg InsertPoliticalReceivedChronicleParams) error {
	_, err := q.db.Exec(ctx, insertPoliticalReceivedChronicle,
		arg.OccurredTick,
		arg.OccurredGameDay,
		arg.ActorID,
		arg.Data,
		arg.HouseholdID,
		arg.WorldEventID,
	)
	return err
}

const listEligiblePoliticalCharacters = `-- name: ListEligiblePoliticalCharacters :many
SELECT c.id::text AS id, c.name, c.labor_capacity_milli
FROM characters c
JOIN household_decisions d ON d.household_id = c.household_id
WHERE d.id = $1::uuid
  AND d.status = 'pending'
  AND d.decision_type = 'political_labor_service'
  AND c.status = 'active' AND c.labor_capacity_milli = 1000
  AND NOT EXISTS (
    SELECT 1 FROM assignments a
    WHERE a.character_id = c.id AND a.status IN ('planned','active')
      AND a.starts_tick <= d.expires_tick + (d.parameters->>'service_ticks')::bigint - 1
      AND a.ends_tick >= d.expires_tick
  )
ORDER BY c.name, c.id
`

type ListEligiblePoliticalCharactersRow struct {
	ID                 string
	Name               string
	LaborCapacityMilli int32
}

func (q *Queries) ListEligiblePoliticalCharacters(ctx context.Context, decisionID pgtype.UUID) ([]ListEligiblePoliticalCharactersRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePoliticalCharacters, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligiblePoliticalCharactersRow{}
	for rows.Next() {
		var i ListEligiblePoliticalCharactersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LaborCapacityMilli); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForPoliticalEvent = `-- name: ListHouseholdsForPoliticalEvent :many
SELECT h.id::text AS household_id, h.world_id::text AS world_id, h.location_id::text AS location_id
FROM households h
JOIN world_events e ON e.location_id = h.location_id AND e.world_id = h.world_id
WHERE e.id = $1::uuid
ORDER BY h.id
`

type ListHouseholdsForPoliticalEventRow struct {
	HouseholdID string
	WorldID     string
	LocationID  string
}

func (q *Queries) ListHouseholdsForPoliticalEvent(ctx context.Context, worldEventID pgtype.UUID) ([]ListHouseholdsForPoliticalEventRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForPoliticalEvent, worldEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdsForPoliticalEventRow{}
	for rows.Next() {
		var i ListHouseholdsForPoliticalEventRow
		if err := rows.Scan(&i.HouseholdID, &i.WorldID, &i.LocationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliticalDecisionsForHousehold = `-- name: ListPoliticalDecisionsForHousehold :many
SELECT d.id::text AS id, d.decision_type, d.available_from_tick, d.expires_tick, d.status,
       d.available_from_game_day, d.expires_game_day, d.selected_option, d.standing_delta, d.parameters,
       e.political_actor_id::text AS political_actor_id, a.name AS actor_name, a.actor_type
FROM household_decisions d JOIN world_events e ON e.id = d.world_event_id
JOIN political_actors a ON a.id = e.political_actor_id
WHERE d.household_id = $1::uuid
ORDER BY d.expires_tick DESC, d.id DESC
`

type ListPoliticalDecisionsForHouseholdRow struct {
	ID                   string
	DecisionType         string
	AvailableFromTick    int64
	ExpiresTick          int64
	Status               string
	AvailableFromGameDay int64
	ExpiresGameDay       int64
	SelectedOption       pgtype.Text
	StandingDelta        pgtype.Int4
	Parameters           []byte
	PoliticalActorID     string
	ActorName            string
	ActorType            string
}

func (q *Queries) ListPoliticalDecisionsForHousehold(ctx context.Context, householdID pgtype.UUID) ([]ListPoliticalDecisionsForHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listPoliticalDecisionsForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliticalDecisionsForHouseholdRow{}
	for rows.Next() {
		var i ListPoliticalDecisionsForHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.DecisionType,
			&i.AvailableFromTick,
			&i.ExpiresTick,
			&i.Status,
			&i.AvailableFromGameDay,
			&i.ExpiresGameDay,
			&i.SelectedOption,
			&i.StandingDelta,
			&i.Parameters,
			&i.PoliticalActorID,
			&i.ActorName,
			&i.ActorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliticalRelationshipsForHousehold = `-- name: ListPoliticalRelationshipsForHousehold :many
SELECT r.political_actor_id::text AS political_actor_id, a.name AS actor_name, a.actor_type,
       r.standing, r.updated_at
FROM political_relationships r JOIN political_actors a ON a.id = r.political_actor_id
WHERE r.world_id = (SELECT world_id FROM households WHERE id = $1::uuid)
  AND r.household_id = $1::uuid ORDER BY a.name
`

type ListPoliticalRelationshipsForHouseholdRow struct {
	PoliticalActorID string
	ActorName        string
	ActorType        string
	Standing         int32
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListPoliticalRelationshipsForHousehold(ctx context.Context, householdID pgtype.UUID) ([]ListPoliticalRelationshipsForHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listPoliticalRelationshipsForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliticalRelationshipsForHouseholdRow{}
	for rows.Next() {
		var i ListPoliticalRelationshipsForHouseholdRow
		if err := rows.Scan(
			&i.PoliticalActorID,
			&i.ActorName,
			&i.ActorType,
			&i.Standing,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadExpiringPoliticalDecisions = `-- name: LoadExpiringPoliticalDecisions :many
SELECT d.id::text AS id, d.household_id::text AS household_id, d.world_id::text AS world_id,
       d.world_event_id::text AS world_event_id, d.decision_type, d.available_from_tick,
       d.expires_tick, d.available_from_game_day, d.expires_game_day, d.status,
       d.selected_option, d.default_option, d.standing_delta, d.parameters,
       e.political_actor_id::text AS political_actor_id, e.event_type
FROM household_decisions d
JOIN world_events e ON e.id = d.world_event_id
WHERE d.world_id = $1::uuid AND d.expires_tick = $2
  AND d.status = 'pending'
ORDER BY d.id
FOR UPDATE OF d
`

type LoadExpiringPoliticalDecisionsParams struct {
	WorldID pgtype.UUID
	Tick    int64
}

type LoadExpiringPoliticalDecisionsRow struct {
	ID                   string
	HouseholdID          string
	WorldID              string
	WorldEventID         string
	DecisionType         string
	AvailableFromTick    int64
	ExpiresTick          int64
	AvailableFromGameDay int64
	ExpiresGameDay       int64
	Status               string
	SelectedOption       pgtype.Text
	DefaultOption        string
	StandingDelta        pgtype.Int4
	Parameters           []byte
	PoliticalActorID     string
	EventType            string
}

func (q *Queries) LoadExpiringPoliticalDecisions(ctx context.Context, arg LoadExpiringPoliticalDecisionsParams) ([]LoadExpiringPoliticalDecisionsRow, error) {
	rows, err := q.db.Query(ctx, loadExpiringPoliticalDecisions, arg.WorldID, arg.Tick)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadExpiringPoliticalDecisionsRow{}
	for rows.Next() {
		var i LoadExpiringPoliticalDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.WorldID,
			&i.WorldEventID,
			&i.DecisionType,
			&i.AvailableFromTick,
			&i.ExpiresTick,
			&i.AvailableFromGameDay,
			&i.ExpiresGameDay,
			&i.Status,
			&i.SelectedOption,
			&i.DefaultOption,
			&i.StandingDelta,
			&i.Parameters,
			&i.PoliticalActorID,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadPoliticalCharacter = `-- name: LoadPoliticalCharacter :one
SELECT c.id::text AS id, c.household_id::text AS household_id, c.status,
       c.labor_capacity_milli
FROM characters c WHERE c.id = $1::uuid
  AND c.household_id = $2::uuid FOR UPDATE
`

type LoadPoliticalCharacterParams struct {
	CharacterID pgtype.UUID
	HouseholdID pgtype.UUID
}

type LoadPoliticalCharacterRow struct {
	ID                 string
	HouseholdID        string
	Status             string
	LaborCapacityMilli int32
}

func (q *Queries) LoadPoliticalCharacter(ctx context.Context, arg LoadPoliticalCharacterParams) (LoadPoliticalCharacterRow, error) {
	row := q.db.QueryRow(ctx, loadPoliticalCharacter, arg.CharacterID, arg.HouseholdID)
	var i LoadPoliticalCharacterRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Status,
		&i.LaborCapacityMilli,
	)
	return i, err
}

const loadPoliticalEventsStartingTick = `-- name: LoadPoliticalEventsStartingTick :many
SELECT e.id::text AS id, e.world_id::text AS world_id, e.location_id::text AS location_id,
       e.political_actor_id::text AS political_actor_id, e.event_type, e.starts_tick,
       e.ends_tick,
       w.current_tick, w.current_game_day, w.calendar_remainder,
       w.game_days_per_tick_num, w.game_days_per_tick_den,
       e.parameters, a.name AS actor_name, a.actor_type
FROM world_events e
JOIN political_actors a ON a.id = e.political_actor_id
JOIN worlds w ON w.id = e.world_id
WHERE e.world_id = $1::uuid
  AND e.starts_tick = $2
  AND e.event_type IN ('political_labor_service','political_levy')
  AND e.political_actor_id IS NOT NULL
ORDER BY e.id
`

type LoadPoliticalEventsStartingTickParams struct {
	WorldID pgtype.UUID
	Tick    int64
}

type LoadPoliticalEventsStartingTickRow struct {
	ID                 string
	WorldID            string
	LocationID         string
	PoliticalActorID   string
	EventType          string
	StartsTick         int64
	EndsTick           pgtype.Int8
	CurrentTick        int64
	CurrentGameDay     int64
	CalendarRemainder  int64
	GameDaysPerTickNum int64
	GameDaysPerTickDen int64
	Parameters         []byte
	ActorName          string
	ActorType          string
}

func (q *Queries) LoadPoliticalEventsStartingTick(ctx context.Context, arg LoadPoliticalEventsStartingTickParams) ([]LoadPoliticalEventsStartingTickRow, error) {
	rows, err := q.db.Query(ctx, loadPoliticalEventsStartingTick, arg.WorldID, arg.Tick)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadPoliticalEventsStartingTickRow{}
	for rows.Next() {
		var i LoadPoliticalEventsStartingTickRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.LocationID,
			&i.PoliticalActorID,
			&i.EventType,
			&i.StartsTick,
			&i.EndsTick,
			&i.CurrentTick,
			&i.CurrentGameDay,
			&i.CalendarRemainder,
			&i.GameDaysPerTickNum,
			&i.GameDaysPerTickDen,
			&i.Parameters,
			&i.ActorName,
			&i.ActorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPoliticalDecision = `-- name: LockPoliticalDecision :one
SELECT d.id::text AS id, d.household_id::text AS household_id, d.world_id::text AS world_id,
       d.world_event_id::text AS world_event_id, d.decision_type, d.available_from_tick,
       d.expires_tick, d.available_from_game_day, d.expires_game_day, d.status,
       d.selected_option, d.default_option, d.standing_delta, d.parameters,
       e.political_actor_id::text AS political_actor_id, e.event_type,
       w.current_tick, w.current_game_day
FROM household_decisions d
JOIN world_events e ON e.id = d.world_event_id
JOIN worlds w ON w.id = d.world_id
WHERE d.id = $1::uuid AND d.household_id = $2::uuid
FOR UPDATE OF d, w
`

type LockPoliticalDecisionParams struct {
	DecisionID  pgtype.UUID
	HouseholdID pgtype.UUID
}

type LockPoliticalDecisionRow struct {
	ID                   string
	HouseholdID          string
	WorldID              string
	WorldEventID         string
	DecisionType         string
	AvailableFromTick    int64
	ExpiresTick          int64
	AvailableFromGameDay int64
	ExpiresGameDay       int64
	Status               string
	SelectedOption       pgtype.Text
	DefaultOption        string
	StandingDelta        pgtype.Int4
	Parameters           []byte
	PoliticalActorID     string
	EventType            string
	CurrentTick          int64
	CurrentGameDay       int64
}

func (q *Queries) LockPoliticalDecision(ctx context.Context, arg LockPoliticalDecisionParams) (LockPoliticalDecisionRow, error) {
	row := q.db.QueryRow(ctx, lockPoliticalDecision, arg.DecisionID, arg.HouseholdID)
	var i LockPoliticalDecisionRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.WorldID,
		&i.WorldEventID,
		&i.DecisionType,
		&i.AvailableFromTick,
		&i.ExpiresTick,
		&i.AvailableFromGameDay,
		&i.ExpiresGameDay,
		&i.Status,
		&i.SelectedOption,
		&i.DefaultOption,
		&i.StandingDelta,
		&i.Parameters,
		&i.PoliticalActorID,
		&i.EventType,
		&i.CurrentTick,
		&i.CurrentGameDay,
	)
	return i, err
}

const lockPoliticalRelationshipScore = `-- name: LockPoliticalRelationshipScore :one
SELECT standing FROM political_relationships
WHERE world_id = $1::uuid AND household_id = $2::uuid
  AND political_actor_id = $3::uuid
FOR UPDATE
`

type LockPoliticalRelationshipScoreParams struct {
	WorldID          pgtype.UUID
	HouseholdID      pgtype.UUID
	PoliticalActorID pgtype.UUID
}

func (q *Queries) LockPoliticalRelationshipScore(ctx context.Context, arg LockPoliticalRelationshipScoreParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockPoliticalRelationshipScore, arg.WorldID, arg.HouseholdID, arg.PoliticalActorID)
	var standing int32
	err := row.Scan(&standing)
	return standing, err
}

const lockResourceStock = `-- name: LockResourceStock :one
SELECT quantity_milli FROM resource_stocks
WHERE household_id = $1::uuid AND resource_code = $2
FOR UPDATE
`

type LockResourceStockParams struct {
	HouseholdID  pgtype.UUID
	ResourceCode string
}

func (q *Queries) LockResourceStock(ctx context.Context, arg LockResourceStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockResourceStock, arg.HouseholdID, arg.ResourceCode)
	var quantity_milli int64
	err := row.Scan(&quantity_milli)
	return quantity_milli, err
}

const resolvePoliticalDecision = `-- name: ResolvePoliticalDecision :execrows
UPDATE household_decisions
SET status = 'resolved', selected_option = $1, resolved_tick = $2,
    standing_delta = $3, related_assignment_id = NULLIF($4::text, '')::uuid,
    updated_at = now()
WHERE id = $5::uuid AND status = 'pending'
`

type ResolvePoliticalDecisionParams struct {
	SelectedOption pgtype.Text
	ResolvedTick   pgtype.Int8
	StandingDelta  pgtype.Int4
	AssignmentID   string
	DecisionID     pgtype.UUID
}

func (q *Queries) ResolvePoliticalDecision(ctx context.Context, arg ResolvePoliticalDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolvePoliticalDecision,
		arg.SelectedOption,
		arg.ResolvedTick,
		arg.StandingDelta,
		arg.AssignmentID,
		arg.DecisionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
