// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimDueWorld(ctx context.Context) (ClaimDueWorldRow, error)
	CreateContract(ctx context.Context, arg CreateContractParams) (CreateContractRow, error)
	CreateContractObligation(ctx context.Context, arg CreateContractObligationParams) error
	CreateContractTerm(ctx context.Context, arg CreateContractTermParams) error
	GetContract(ctx context.Context, dollar_1 pgtype.UUID) (GetContractRow, error)
	GetRouteDistance(ctx context.Context, arg GetRouteDistanceParams) (string, error)
	IsWorldTickProcessed(ctx context.Context, arg IsWorldTickProcessedParams) (bool, error)
	LinkContractObligationShipment(ctx context.Context, arg LinkContractObligationShipmentParams) (int64, error)
	ListActiveContractsForRollup(ctx context.Context, dollar_1 pgtype.UUID) ([]ListActiveContractsForRollupRow, error)
	ListActiveMarketOffers(ctx context.Context, dollar_1 pgtype.UUID) ([]ListActiveMarketOffersRow, error)
	ListContractObligations(ctx context.Context, dollar_1 pgtype.UUID) ([]ListContractObligationsRow, error)
	ListContractTerms(ctx context.Context, dollar_1 pgtype.UUID) ([]ListContractTermsRow, error)
	ListContractsForHousehold(ctx context.Context, dollar_1 pgtype.UUID) ([]ListContractsForHouseholdRow, error)
	ListShipmentsByHousehold(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByHouseholdRow, error)
	ListShipmentsByWorld(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByWorldRow, error)
	LoadContractObligationsForTick(ctx context.Context, arg LoadContractObligationsForTickParams) ([]LoadContractObligationsForTickRow, error)
	LoadShipmentsDueForArrival(ctx context.Context, arg LoadShipmentsDueForArrivalParams) ([]LoadShipmentsDueForArrivalRow, error)
	LockContractForResponse(ctx context.Context, dollar_1 pgtype.UUID) (LockContractForResponseRow, error)
	LockContractObligationForDispatch(ctx context.Context, dollar_1 pgtype.UUID) (LockContractObligationForDispatchRow, error)
	LockMarketOffer(ctx context.Context, dollar_1 pgtype.UUID) (LockMarketOfferRow, error)
	MarkShipmentArrived(ctx context.Context, arg MarkShipmentArrivedParams) (string, error)
	MarkWorldTickProcessed(ctx context.Context, arg MarkWorldTickProcessedParams) error
	UpdateContractObligationAssessment(ctx context.Context, arg UpdateContractObligationAssessmentParams) (int64, error)
	UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) (int64, error)
	UpdateMarketOfferAfterPurchase(ctx context.Context, arg UpdateMarketOfferAfterPurchaseParams) (UpdateMarketOfferAfterPurchaseRow, error)
}

var _ Querier = (*Queries)(nil)
