// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimDueWorld(ctx context.Context) (ClaimDueWorldRow, error)
	GetMarketRouteDistance(ctx context.Context, arg GetMarketRouteDistanceParams) (string, error)
	IsWorldTickProcessed(ctx context.Context, arg IsWorldTickProcessedParams) (bool, error)
	ListActiveMarketOffers(ctx context.Context, dollar_1 pgtype.UUID) ([]ListActiveMarketOffersRow, error)
	ListShipmentsByHousehold(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByHouseholdRow, error)
	ListShipmentsByWorld(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByWorldRow, error)
	LoadShipmentsDueForArrival(ctx context.Context, arg LoadShipmentsDueForArrivalParams) ([]LoadShipmentsDueForArrivalRow, error)
	LockMarketOffer(ctx context.Context, dollar_1 pgtype.UUID) (LockMarketOfferRow, error)
	MarkShipmentArrived(ctx context.Context, arg MarkShipmentArrivedParams) (string, error)
	MarkWorldTickProcessed(ctx context.Context, arg MarkWorldTickProcessedParams) error
	UpdateMarketOfferAfterPurchase(ctx context.Context, arg UpdateMarketOfferAfterPurchaseParams) (UpdateMarketOfferAfterPurchaseRow, error)
}

var _ Querier = (*Queries)(nil)
