// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyRelationshipDelta = `-- name: ApplyRelationshipDelta :exec
INSERT INTO relationships(
    world_id, source_household_id, target_household_id,
    trust, first_interaction_tick, updated_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    now()
)
ON CONFLICT (source_household_id, target_household_id)
DO UPDATE SET
    trust = GREATEST(-100, LEAST(100, relationships.trust + EXCLUDED.trust)),
    first_interaction_tick = LEAST(relationships.first_interaction_tick, EXCLUDED.first_interaction_tick),
    updated_at = now()
`

type ApplyRelationshipDeltaParams struct {
	WorldID           pgtype.UUID
	SourceHouseholdID pgtype.UUID
	TargetHouseholdID pgtype.UUID
	TrustDelta        int32
	OccurredTick      pgtype.Int8
}

func (q *Queries) ApplyRelationshipDelta(ctx context.Context, arg ApplyRelationshipDeltaParams) error {
	_, err := q.db.Exec(ctx, applyRelationshipDelta,
		arg.WorldID,
		arg.SourceHouseholdID,
		arg.TargetHouseholdID,
		arg.TrustDelta,
		arg.OccurredTick,
	)
	return err
}

const insertRelationshipEvent = `-- name: InsertRelationshipEvent :execrows
INSERT INTO relationship_events(
    world_id, source_household_id, target_household_id,
    event_type, trust_delta, occurred_tick,
    related_contract_id, related_shipment_id, related_obligation_id, data
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    $7::uuid,
    NULLIF($8::text, '')::uuid,
    $9::uuid,
    jsonb_build_object(
        'resource_type', $10::text,
        'quantity_milli', $11::bigint,
        'due_arrival_tick', $12::bigint,
        'actual_fulfillment_tick', $13::bigint
    )
)
ON CONFLICT (source_household_id, target_household_id, event_type, related_obligation_id)
WHERE related_obligation_id IS NOT NULL
DO NOTHING
`

type InsertRelationshipEventParams struct {
	WorldID               pgtype.UUID
	SourceHouseholdID     pgtype.UUID
	TargetHouseholdID     pgtype.UUID
	EventType             string
	TrustDelta            int32
	OccurredTick          int64
	ContractID            pgtype.UUID
	ShipmentID            string
	ObligationID          pgtype.UUID
	ResourceType          string
	QuantityMilli         int64
	DueArrivalTick        int64
	ActualFulfillmentTick pgtype.Int8
}

func (q *Queries) InsertRelationshipEvent(ctx context.Context, arg InsertRelationshipEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRelationshipEvent,
		arg.WorldID,
		arg.SourceHouseholdID,
		arg.TargetHouseholdID,
		arg.EventType,
		arg.TrustDelta,
		arg.OccurredTick,
		arg.ContractID,
		arg.ShipmentID,
		arg.ObligationID,
		arg.ResourceType,
		arg.QuantityMilli,
		arg.DueArrivalTick,
		arg.ActualFulfillmentTick,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
