// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listShipmentsByHousehold = `-- name: ListShipmentsByHousehold :many
SELECT id::text AS id, world_id::text AS world_id,
       sender_household_id::text AS sender_household_id,
       receiver_household_id::text AS receiver_household_id,
       origin_location_id::text AS origin_location_id,
       destination_location_id::text AS destination_location_id,
       resource_code, quantity_milli, departure_tick, expected_arrival_tick,
       actual_arrival_tick, departure_game_day, expected_arrival_game_day,
       actual_arrival_game_day, transport_cost_milli, status
FROM shipments
WHERE sender_household_id = $1::uuid OR receiver_household_id = $1::uuid
ORDER BY departure_tick DESC, id
`

type ListShipmentsByHouseholdRow struct {
	ID                     string
	WorldID                string
	SenderHouseholdID      string
	ReceiverHouseholdID    string
	OriginLocationID       string
	DestinationLocationID  string
	ResourceCode           string
	QuantityMilli          int64
	DepartureTick          int64
	ExpectedArrivalTick    int64
	ActualArrivalTick      pgtype.Int8
	DepartureGameDay       pgtype.Int8
	ExpectedArrivalGameDay int64
	ActualArrivalGameDay   pgtype.Int8
	TransportCostMilli     int64
	Status                 string
}

func (q *Queries) ListShipmentsByHousehold(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listShipmentsByHousehold, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentsByHouseholdRow{}
	for rows.Next() {
		var i ListShipmentsByHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.SenderHouseholdID,
			&i.ReceiverHouseholdID,
			&i.OriginLocationID,
			&i.DestinationLocationID,
			&i.ResourceCode,
			&i.QuantityMilli,
			&i.DepartureTick,
			&i.ExpectedArrivalTick,
			&i.ActualArrivalTick,
			&i.DepartureGameDay,
			&i.ExpectedArrivalGameDay,
			&i.ActualArrivalGameDay,
			&i.TransportCostMilli,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsByWorld = `-- name: ListShipmentsByWorld :many
SELECT id::text AS id, world_id::text AS world_id,
       sender_household_id::text AS sender_household_id,
       receiver_household_id::text AS receiver_household_id,
       origin_location_id::text AS origin_location_id,
       destination_location_id::text AS destination_location_id,
       resource_code, quantity_milli, departure_tick, expected_arrival_tick,
       actual_arrival_tick, departure_game_day, expected_arrival_game_day,
       actual_arrival_game_day, transport_cost_milli, status
FROM shipments
WHERE world_id = $1::uuid
ORDER BY departure_tick DESC, id
`

type ListShipmentsByWorldRow struct {
	ID                     string
	WorldID                string
	SenderHouseholdID      string
	ReceiverHouseholdID    string
	OriginLocationID       string
	DestinationLocationID  string
	ResourceCode           string
	QuantityMilli          int64
	DepartureTick          int64
	ExpectedArrivalTick    int64
	ActualArrivalTick      pgtype.Int8
	DepartureGameDay       pgtype.Int8
	ExpectedArrivalGameDay int64
	ActualArrivalGameDay   pgtype.Int8
	TransportCostMilli     int64
	Status                 string
}

func (q *Queries) ListShipmentsByWorld(ctx context.Context, dollar_1 pgtype.UUID) ([]ListShipmentsByWorldRow, error) {
	rows, err := q.db.Query(ctx, listShipmentsByWorld, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentsByWorldRow{}
	for rows.Next() {
		var i ListShipmentsByWorldRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.SenderHouseholdID,
			&i.ReceiverHouseholdID,
			&i.OriginLocationID,
			&i.DestinationLocationID,
			&i.ResourceCode,
			&i.QuantityMilli,
			&i.DepartureTick,
			&i.ExpectedArrivalTick,
			&i.ActualArrivalTick,
			&i.DepartureGameDay,
			&i.ExpectedArrivalGameDay,
			&i.ActualArrivalGameDay,
			&i.TransportCostMilli,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadShipmentsDueForArrival = `-- name: LoadShipmentsDueForArrival :many
SELECT id::text AS id, world_id::text AS world_id,
       sender_household_id::text AS sender_household_id,
       receiver_household_id::text AS receiver_household_id,
       origin_location_id::text AS origin_location_id,
       destination_location_id::text AS destination_location_id,
       resource_code, quantity_milli, departure_tick, expected_arrival_tick,
       actual_arrival_tick, departure_game_day, expected_arrival_game_day,
       actual_arrival_game_day, transport_cost_milli, status
FROM shipments
WHERE world_id = $1::uuid
  AND status = 'in_transit'
  AND actual_arrival_tick IS NULL
  AND expected_arrival_tick <= $2
ORDER BY expected_arrival_tick, id
FOR UPDATE
`

type LoadShipmentsDueForArrivalParams struct {
	Column1             pgtype.UUID
	ExpectedArrivalTick int64
}

type LoadShipmentsDueForArrivalRow struct {
	ID                     string
	WorldID                string
	SenderHouseholdID      string
	ReceiverHouseholdID    string
	OriginLocationID       string
	DestinationLocationID  string
	ResourceCode           string
	QuantityMilli          int64
	DepartureTick          int64
	ExpectedArrivalTick    int64
	ActualArrivalTick      pgtype.Int8
	DepartureGameDay       pgtype.Int8
	ExpectedArrivalGameDay int64
	ActualArrivalGameDay   pgtype.Int8
	TransportCostMilli     int64
	Status                 string
}

func (q *Queries) LoadShipmentsDueForArrival(ctx context.Context, arg LoadShipmentsDueForArrivalParams) ([]LoadShipmentsDueForArrivalRow, error) {
	rows, err := q.db.Query(ctx, loadShipmentsDueForArrival, arg.Column1, arg.ExpectedArrivalTick)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadShipmentsDueForArrivalRow{}
	for rows.Next() {
		var i LoadShipmentsDueForArrivalRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.SenderHouseholdID,
			&i.ReceiverHouseholdID,
			&i.OriginLocationID,
			&i.DestinationLocationID,
			&i.ResourceCode,
			&i.QuantityMilli,
			&i.DepartureTick,
			&i.ExpectedArrivalTick,
			&i.ActualArrivalTick,
			&i.DepartureGameDay,
			&i.ExpectedArrivalGameDay,
			&i.ActualArrivalGameDay,
			&i.TransportCostMilli,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShipmentArrived = `-- name: MarkShipmentArrived :one
UPDATE shipments
SET status = 'arrived', actual_arrival_tick = $2, actual_arrival_game_day = $4
WHERE id = $1::uuid
  AND world_id = $3::uuid
  AND status = 'in_transit'
  AND actual_arrival_tick IS NULL
  AND expected_arrival_tick <= $2
RETURNING id::text
`

type MarkShipmentArrivedParams struct {
	Column1              pgtype.UUID
	ActualArrivalTick    pgtype.Int8
	Column3              pgtype.UUID
	ActualArrivalGameDay pgtype.Int8
}

func (q *Queries) MarkShipmentArrived(ctx context.Context, arg MarkShipmentArrivedParams) (string, error) {
	row := q.db.QueryRow(ctx, markShipmentArrived,
		arg.Column1,
		arg.ActualArrivalTick,
		arg.Column3,
		arg.ActualArrivalGameDay,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
