// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHouseholdOccupations = `-- name: ListHouseholdOccupations :many
SELECT c.id::text AS character_id, c.name, c.status, c.labor_capacity_milli,
       COALESCE(o.activity, CASE h.specialization WHEN 'forest' THEN 'woodcutting' ELSE COALESCE(h.specialization, 'agriculture') END) AS activity,
       o.pending_activity, o.effective_game_day, COALESCE(o.revision, 1) AS revision
FROM characters c
JOIN households h ON h.id = c.household_id
LEFT JOIN character_occupations o ON o.character_id = c.id
WHERE c.household_id = $1::uuid AND c.status <> 'dead'
ORDER BY c.created_at, c.id
`

type ListHouseholdOccupationsRow struct {
	CharacterID        string
	Name               string
	Status             string
	LaborCapacityMilli int32
	Activity           string
	PendingActivity    pgtype.Text
	EffectiveGameDay   pgtype.Int8
	Revision           int64
}

func (q *Queries) ListHouseholdOccupations(ctx context.Context, householdID pgtype.UUID) ([]ListHouseholdOccupationsRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdOccupations, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdOccupationsRow{}
	for rows.Next() {
		var i ListHouseholdOccupationsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.Status,
			&i.LaborCapacityMilli,
			&i.Activity,
			&i.PendingActivity,
			&i.EffectiveGameDay,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOccupation = `-- name: SaveOccupation :exec
INSERT INTO character_occupations(character_id, activity, pending_activity, effective_game_day, revision)
VALUES ($1::uuid, $2, $3, $4, $5)
ON CONFLICT (character_id) DO UPDATE SET activity = EXCLUDED.activity,
  pending_activity = EXCLUDED.pending_activity, effective_game_day = EXCLUDED.effective_game_day,
  revision = EXCLUDED.revision
`

type SaveOccupationParams struct {
	CharacterID      pgtype.UUID
	Activity         string
	PendingActivity  pgtype.Text
	EffectiveGameDay pgtype.Int8
	Revision         int64
}

func (q *Queries) SaveOccupation(ctx context.Context, arg SaveOccupationParams) error {
	_, err := q.db.Exec(ctx, saveOccupation,
		arg.CharacterID,
		arg.Activity,
		arg.PendingActivity,
		arg.EffectiveGameDay,
		arg.Revision,
	)
	return err
}
