// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worlds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWorld = `-- name: ClaimDueWorld :one
SELECT id::text AS id, current_tick, tick_duration_seconds, next_tick_at
FROM worlds
WHERE next_tick_at <= now()
ORDER BY next_tick_at
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type ClaimDueWorldRow struct {
	ID                  string
	CurrentTick         int64
	TickDurationSeconds int32
	NextTickAt          pgtype.Timestamptz
}

func (q *Queries) ClaimDueWorld(ctx context.Context) (ClaimDueWorldRow, error) {
	row := q.db.QueryRow(ctx, claimDueWorld)
	var i ClaimDueWorldRow
	err := row.Scan(
		&i.ID,
		&i.CurrentTick,
		&i.TickDurationSeconds,
		&i.NextTickAt,
	)
	return i, err
}

const isWorldTickProcessed = `-- name: IsWorldTickProcessed :one
SELECT EXISTS (
    SELECT 1 FROM processed_world_ticks
    WHERE world_id = $1::uuid AND tick = $2
)
`

type IsWorldTickProcessedParams struct {
	Column1 pgtype.UUID
	Tick    int64
}

func (q *Queries) IsWorldTickProcessed(ctx context.Context, arg IsWorldTickProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorldTickProcessed, arg.Column1, arg.Tick)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markWorldTickProcessed = `-- name: MarkWorldTickProcessed :exec
INSERT INTO processed_world_ticks (world_id, tick)
VALUES ($1::uuid, $2)
ON CONFLICT DO NOTHING
`

type MarkWorldTickProcessedParams struct {
	Column1 pgtype.UUID
	Tick    int64
}

func (q *Queries) MarkWorldTickProcessed(ctx context.Context, arg MarkWorldTickProcessedParams) error {
	_, err := q.db.Exec(ctx, markWorldTickProcessed, arg.Column1, arg.Tick)
	return err
}
